### ISSUE TITLE
An error happens when running with npx

### ISSUE THREAD

**Issue by hossammourad** [vladocar/PDFSave#1]
```
npx pdfsave --url http:www.example.com
npx: installed 197 in 12.524s
/Users/hossammourad/.npm/_npx/45167/lib/node_modules/pdfsave/index.js:26
    var result = stripHTML(article.content);
                                   ^
TypeError: Cannot read property 'content' of undefined
    at /Users/hossammourad/.npm/_npx/45167/lib/node_modules/pdfsave/index.js:26:36
    at Request._callback (/Users/hossammourad/.npm/_npx/45167/lib/node_modules/pdfsave/node_modules/node-readability/src/readability.js:219:16)
    at self.callback (/Users/hossammourad/.npm/_npx/45167/lib/node_modules/pdfsave/node_modules/request/request.js:123:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at ClientRequest.self.clientErrorHandler (/Users/hossammourad/.npm/_npx/45167/lib/node_modules/pdfsave/node_modules/request/request.js:244:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
```

**Comment by vladocar** [comment]
Sorry I forgot to put "//".

In the docs now is : pdfsave --url http:www.example.com
But it should be:  pdfsave --url http://www.example.com

Try like this with a real web site:

pdfsave --url https://www.lipsum.com

I will update the docs.
